name: Windows test

on:
  push:
    branches:
      - windows-test
  workflow_dispatch:

jobs:
  build_on_win:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - run: npm install
      - run: npm run build
